apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: team13-ns
data:
  POSTGRES_HOST: "79.174.89.43"
  POSTGRES_PORT: "18809"
  POSTGRES_DB: "team13_db"
  POSTGRES_USER: "team13"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ALGORITHM: "HS256"