apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: {{ .Values.namespace | quote }}
data:
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  ALGORITHM: {{ .Values.auth.algorithm | quote }}