apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: team13-ns
data:
  AUTH_SERVICE_BASE_URL: {{ .Values.auth.baseUrl | quote }}
  HABR_ADAPTER_BASE_URL: {{ .Values.habr.baseUrl | quote }}
  LLM_SERVICE_BASE_URL: {{ .Values.llm.baseUrl | quote }}
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.user | quote }}
  ARTICLE_QUEUE_NAME: {{ .Values.rabbitmq.queueName | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
