apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-service-config
  namespace: team13-ns
data:
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.user | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  LLM_RATE_LIMIT: {{ .Values.llm.llmRateLimitPerMinute | quote }}
  LLM_HOURLY_LIMIT: {{ .Values.llm.llmMaxHourlyRequests | quote }}
